name: Electron Builder CI

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    env:
      CC: clang
      CXX: clang++ 
      npm_config_clang: 1
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OS_NAME: ${{ matrix.os }}
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
    - name: Installing Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Build for ${{ matrix.os}}
      run: |
        if [ "$OS_NAME" = "ubuntu-18.04" ]; then sudo apt-get update && sudo apt-get install -y libgnome-keyring-dev icnsutils graphicsmagick xz-utils rpm; fi
        curl -o- -L https://yarnpkg.com/install.sh | bash
        export PATH="$HOME/.yarn/bin:$PATH"
        # Use sed to replace the SSH URL with the public URL, then initialize submodules
        sed -ie 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        git submodule update --init --recursive
        sudo npm install -g yarn
        yarn install
        if [ "$OS_NAME" = "ubuntu-18.04" ]; then sed -ie 's/"asar": true,/"asar": true,\n"productName": "drawio",/' electron-builder-linux-mac.json; fi 
        yarn run sync
        yarn run release-linux
